# -*- coding: utf-8 -*-
"""etl-proveedores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvsgAPtS82rc4BTlreH55_k1GeOZKD4O

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
#En esta url va nuestra base de datos (En este caso en render)
database_url = "postgresql://etl_seguros_fwgm_user:FLIwCR2BnSl9vmgdqKd7GtpzOyBHRpyl@dpg-d6qu5hk50q8c73bpe0p0-a.oregon-postgres.render.com/etl_seguros_fwgm"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline-25-1449-2022/refs/heads/main/data/raw/B_proveedores.csv"
proveedores = pd.read_csv(url)

"""Exploración de datos"""

proveedores.head()

proveedores.info()

proveedores.isnull().sum()

proveedores.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

proveedores = normalizar_columnas(proveedores)
proveedores = limpiar_texto(proveedores)
proveedores = proveedores.drop_duplicates()

"""Funciones especificas"""

#Normalizar pais

map_pais = {
    "EL SALVADOR": "El Salvador",
    "el salvador": "El Salvador",
    "El Salvador": "El Salvador",

    "GUATEMALA": "Guatemala",
    "guatemala": "Guatemala",
    "Guatemala": "Guatemala",

    "COSTA RICA": "Costa Rica",
    "costa rica": "Costa Rica",
    "Costa Rica": "Costa Rica",

    "HONDURAS": "Honduras",
    "honduras": "Honduras",
    "Honduras": "Honduras"
}


#Limpiar a los proveedores

proveedores["proveedor"] = proveedores["proveedor"].str.replace(r'\s\d+$',"",regex=True)

proveedores.info()

proveedores.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. el proveedor no puede ser nulo ni estar vacio

columnas_obligatorias = [
    "id_proveedor",
    "proveedor"
]

condicion_nulos = proveedores[columnas_obligatorias].isna().any(axis=1)

rechazados = proveedores.loc[condicion_nulos].copy()
validos = proveedores.loc[~condicion_nulos].copy()

"""Motivo del rechazo"""

from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_proveedor"]):
    motivos.append("ID_proveedor_no_valido")

  if pd.isna(row["proveedor"]):
    motivos.append("proveedor_no_valido")

  return ",".join(motivos)

"""Agregar motivo de rechazo"""

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("proveedores_curated.csv", index=False)
rechazados.to_csv("proveedores_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

proveedores.value_counts()

validos.to_sql(
    "proveedores",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From proveedores Limit 100",
    engine
)