# -*- coding: utf-8 -*-
"""etl-productos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvsgAPtS82rc4BTlreH55_k1GeOZKD4O

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
#En esta url va nuestra base de datos (En este caso en render)
database_url = "postgresql://etl_seguros_fwgm_user:FLIwCR2BnSl9vmgdqKd7GtpzOyBHRpyl@dpg-d6qu5hk50q8c73bpe0p0-a.oregon-postgres.render.com/etl_seguros_fwgm"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline-25-1449-2022/refs/heads/main/data/raw/B_productos.csv"
productos = pd.read_csv(url)

"""Exploración de datos"""

productos.head()

productos.info()

productos.isnull().sum()

productos.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

productos = normalizar_columnas(productos)
productos = limpiar_texto(productos)
productos = productos.drop_duplicates()

"""Funciones especificas"""

#Limpiar el precio y convertirlo a float

productos["precio"] = (
    productos["precio"]
    .astype(str)
    .str.extract(r'(\d+\.?\d*)'))[0].astype(float)

productos.info()

productos.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. El stock y la bodega no pueden estar vacios y stock no puede ser negativo

columnas_obligatorias = [
    "id_producto",
    "id_proveedor",
    "precio",
    "producto"
]

condicion_nulos = productos[columnas_obligatorias].isna().any(axis=1)

condicion_precio_invalido = productos["precio"] <= 0

condicion_rechazo = condicion_nulos | condicion_precio_invalido

rechazados = productos.loc[condicion_rechazo].copy()
validos = productos.loc[~condicion_rechazo].copy()

"""Motivo del rechazo"""

from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_producto"]):
    motivos.append("ID_productos_no_valido")

  if pd.isna(row["id_proveedor"]):
    motivos.append("ID_proveedor_no_valido")

  if pd.isna(row["precio"]):
    motivos.append("precio_no_valido")

  if pd.isna(row["producto"]):
    motivos.append("producto_no_valido")

  elif row["precio"] < 0:
      motivos.append("precio_no_puede_ser_negativo")

  return ",".join(motivos)

"""Agregar motivo de rechazo"""

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("productos_curated.csv", index=False)
rechazados.to_csv("productos_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

productos.value_counts()

validos.to_sql(
    "productos",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From productos Limit 100",
    engine
)