# -*- coding: utf-8 -*-
"""etl-inventario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvsgAPtS82rc4BTlreH55_k1GeOZKD4O

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
#En esta url va nuestra base de datos (En este caso en render)
database_url = "postgresql://etl_seguros_fwgm_user:FLIwCR2BnSl9vmgdqKd7GtpzOyBHRpyl@dpg-d6qu5hk50q8c73bpe0p0-a.oregon-postgres.render.com/etl_seguros_fwgm"
engine = create_engine(database_url)

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline-25-1449-2022/refs/heads/main/data/raw/B_inventario.csv"
inventario = pd.read_csv(url)

"""Exploración de datos"""

inventario.head()

inventario.info()

inventario.isnull().sum()

inventario.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

inventario = normalizar_columnas(inventario)
inventario = limpiar_texto(inventario)
inventario = inventario.drop_duplicates()

"""Funciones especificas"""

#Normalización de bodega

map_bodega = {
    "Transito": "Tránsito",
    "TRANSITO": "Tránsito",

    "CENTRAL": "Central",
    "central": "Central",

    "SUCURSAL 1": "Sucursal 1",
    "sucursal 1": "Sucursal 1",
    "sucursal1" : "Sucursal 1",
    "SUCURSAL1": "Sucursal 1",

    "SUCURSAL 2": "Sucursal 2",
    "sucursal 2": "Sucursal 2",
    "sucursal2" : "Sucursal 2",
    "SUCURSAL2": "Sucursal 2"
}

inventario["bodega"] = (
    inventario["bodega"]
    .astype(str)
    .str.strip()
    .replace(map_bodega)
)

#Limpiar texto

inventario["stock"] = inventario["stock"].astype(str).str.replace("R/D", "", regex=True)

#Convertir a entero

inventario["stock"] = pd.to_numeric(inventario["stock"], errors="coerce")

#Manejar nulos

inventario["stock"] = inventario["stock"].fillna(0).astype(int)

inventario.info()

inventario.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. El stock y la bodega no pueden estar vacios y stock no puede ser negativo

columnas_obligatorias = [
    "id_inventario",
    "id_producto",
    "stock",
    "bodega"
]

condicion_nulos = inventario[columnas_obligatorias].isna().any(axis=1)

condicion_stock_invalido = inventario["stock"] < 0

condicion_rechazo = condicion_nulos | condicion_stock_invalido

rechazados = inventario.loc[condicion_rechazo].copy()
validos = inventario.loc[~condicion_rechazo].copy()

"""Motivo del rechazo"""

from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_inventario"]):
    motivos.append("ID_inventario_no_valido")

  if pd.isna(row["id_producto"]):
    motivos.append("ID_producto_no_valido")

  if pd.isna(row["stock"]):
    motivos.append("stock_invalido")

  if pd.isna(row["bodega"]):
    motivos.append("bodega_invalida")

  elif row["stock"] < 0:
      motivos.append("stock_no_puede_ser_negativo")

  return ",".join(motivos)

"""Agregar motivo de rechazo"""

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("inventario_curated.csv", index=False)
rechazados.to_csv("inventario_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

validos.head()

validos.dtypes

validos.isnull().sum()

inventario.value_counts()

validos.to_sql(
    "inventario",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From inventario Limit 100",
    engine
)